### ISSUE TITLE
ro-crate has lodash as a dependency

### ISSUE THREAD

**Issue by spikelynch** [UTS-eResearch/ro-crate-js#11]
But it isn't in package.json - I guess whenever we're using it we've got lodash included as well so I didn't notice till this afternoon when starting a new project for d3 viz

**Comment by stain** [comment]
Installation fails with:

```json
node_modules/.bin/makehtml --version
module.js:550
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/stain/src/ro-crate/node_modules/ro-crate/lib/ro-crate-preview.js:21:11)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
make: *** [Makefile:19: dependencies] Error 1
```

Workaround:

    npm install lodash
